### ISSUE TITLE
Simplify: Apply shared CSS properties to multiple elements at once to simplify the code.

### ISSUE THREAD

**Issue by josephtkim** [GregPrendergast/prj-rev-bwfs-dasmoto#6]
It is always a good idea to simplify your CSS so that there is less repeated code, and it is concise. Some properties are shared among the elements, and can be applied to them all at once, like

```css
.header, h2, span {
  font-family: Helvetica;
  font-weight: bold;  
}
```
